[project]
name = "gnews-mcp-server"
version = "0.1.0"
description = "A FastMCP server to fetch news from GNews API"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]==1.27.0",
    "python-dotenv==1.2.2",
    "httpx>=0.28.0",
    "typing-extensions==4.15.0",
]

[project.scripts]
# This creates a terminal command 'gnews-mcp' that points to your app instance
gnews-mcp = "app:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
